name: Generate and Publish Documentation

on:
  push:
    branches: [main]
    tags: ["v*"]

jobs:
  build-dokka:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate documentation
        run: ./gradlew dokkaHtml

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: build/dokka/html

      - name: Deploy to GitHub Pages
        if: startsWith(github.ref, 'refs/tags/')
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/dokka/html
          branch: gh-pages
          clean: true
